import { useState } from "react";
import { generateReport } from "../api";

export default function AIReport({ simulationId, llmUsed }) {
  const [report, setReport] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const [reportLlmUsed, setReportLlmUsed] = useState(false);

  const handleGenerate = async () => {
    setLoading(true);
    setError(null);
    try {
      const res = await generateReport(simulationId);
      setReport(res.report);
      setReportLlmUsed(res.llm_used);
    } catch (err) {
      setError(err.message);
    }
    setLoading(false);
  };

  const handleDownload = () => {
    const blob = new Blob([report], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `crisismind-report-${simulationId}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="card report-card">
      <h2 className="section-title">📄 AI Crisis Response Report</h2>

      <div className="report-meta">
        <span className="report-sim-id">Simulation: {simulationId}</span>
        <span className={`report-llm-badge ${llmUsed ? "badge-llm" : "badge-rule"}`}>
          {llmUsed ? "🤖 LLM-Enhanced Explanation" : "⚙️ Rule-Based Explanation"}
        </span>
      </div>

      {!report && (
        <div className="report-intro">
          <p className="muted">
            Generate a full crisis response report for this simulation.
            {" "}{llmUsed
              ? "Ollama LLM is online — report will be AI-generated."
              : "Ollama is offline — report will use rule-based generation."}
          </p>
          <button
            className="btn-primary"
            onClick={handleGenerate}
            disabled={loading}
            style={{ marginTop: "12px" }}
          >
            {loading ? "⏳ Generating Report..." : "📄 Generate AI Report"}
          </button>
        </div>
      )}

      {error && <div className="status-msg status-error">{error}</div>}

      {report && (
        <>
          <div className="report-source-badge">
            {reportLlmUsed
              ? "🤖 Generated by Ollama Local LLM (Privacy-Preserving)"
              : "⚙️ Generated by Rule-Based Engine (Fallback)"}
          </div>
          <pre className="report-content">{report}</pre>
          <div className="btn-row" style={{ marginTop: "14px" }}>
            <button className="btn-primary" onClick={handleDownload}>⬇ Download Report</button>
            <button className="btn-ghost" onClick={() => setReport(null)}>↺ Regenerate</button>
          </div>
        </>
      )}
    </div>
  );
}
